### ISSUE TITLE
aggreprobe function fails when use = "score"

### ISSUE THREAD

**Issue by yangleicq** [Nanostring-Biostats/GeoDiff#2]
![image](https://user-images.githubusercontent.com/1574774/136603423-7dee0e9a-3e94-4c3c-95f9-a57bdd73c5fc.png)

**Comment by NicoleEO** [comment]
@yangleicq it seems this may be old package versioning again. I used the latest NCTools and GeomxTools and it ran through for me. 
![image](https://user-images.githubusercontent.com/20404635/136631543-55bfd452-d6aa-4ca4-ac9e-27186f379155.png)
