### ISSUE TITLE
default values

### ISSUE THREAD

**Issue by maddygriz** [Nanostring-Biostats/GeoDiff#9]
fitNBthDE 
- [x] prior_type = c("equal", "contrast") should be changed to prior_type = c("contrast", "equal")
- [x] preci2 needs a default value
- [x] preci1con needs a default value

fitNBthmDE
- [ ] preci1 needs a default value
- [x] preci2 needs a default value
- [x] threshold_mean needs default value

fitPoisthNorm
- [x] preci2 needs a default value

**Comment by zhiiiyang** [comment]
@maddygriz, preci1 is from another fitted model and can't be pre-specified by a simple fixed number or calculation.
